let legends = [
  { name: "Ada", weapon1: "Blasters", weapon2: "Spear", accentColor: "#A32BC1", stats: { strength: 6, dexterity: 7, defense: 3, speed: 6 } },
  { name: "Arcadia", weapon1: "Spear", weapon2: "Greatsword", accentColor: "#402A4F", stats: { strength: 7, dexterity: 7, defense: 4, speed: 4 } },
  { name: "Artemis", weapon1: "Rocket Lance", weapon2: "Scythe", accentColor: "#656C9E", stats: { strength: 5, dexterity: 5, defense: 4, speed: 8 } },
  { name: "Asuri", weapon1: "Sword", weapon2: "Katars", accentColor: "#ABB5BD", stats: { strength: 4, dexterity: 7, defense: 5, speed: 6 } },
  { name: "Aurus", weapon1: "Spear", weapon2: "Chakram", accentColor: "#81453D", stats: { strength: 6, dexterity: 6, defense: 6, speed: 4 } },
  { name: "Azoth", weapon1: "Axe", weapon2: "Bow", accentColor: "#6D7D4E", stats: { strength: 7, dexterity: 5, defense: 6, speed: 4 } },
  { name: "Barraza", weapon1: "Blasters", weapon2: "Axe", accentColor: "#89D1C9", stats: { strength: 6, dexterity: 4, defense: 8, speed: 4 } },
  { name: "Bodvar", weapon1: "Hammer", weapon2: "Sword", accentColor: "#00B289", stats: { strength: 6, dexterity: 6, defense: 5, speed: 5 } },
  { name: "Brynn", weapon1: "Spear", weapon2: "Axe", accentColor: "#C3D9D6", stats: { strength: 5, dexterity: 5, defense: 5, speed: 7 } },
  { name: "Caspian", weapon1: "Katars", weapon2: "Gauntlets", accentColor: "#a41111", stats: { strength: 7, dexterity: 5, defense: 4, speed: 6 } },
  { name: "Cassidy", weapon1: "Hammer", weapon2: "Blasters", accentColor: "#4B0505", stats: { strength: 6, dexterity: 8, defense: 4, speed: 4 } },
  { name: "Cross", weapon1: "Blasters", weapon2: "Gauntlets", accentColor: "#420505", stats: { strength: 7, dexterity: 4, defense: 6, speed: 5 } },
  { name: "Diana", weapon1: "Blasters", weapon2: "Bow", accentColor: "#5B0A1F", stats: { strength: 5, dexterity: 6, defense: 5, speed: 6 } },
  { name: "Dusk", weapon1: "Spear", weapon2: "Orb", accentColor: "#E8F5FD", stats: { strength: 6, dexterity: 7, defense: 4, speed: 5 } },
  { name: "Ember", weapon1: "Katars", weapon2: "Bow", accentColor: "#6C963F", stats: { strength: 6, dexterity: 6, defense: 3, speed: 7 } },
  { name: "Ezio", weapon1: "Sword", weapon2: "Orb", accentColor: "#F6F6F6", stats: { strength: 5, dexterity: 7, defense: 4, speed: 6 } },
  { name: "Fait", weapon1: "Scythe", weapon2: "Orb", accentColor: "#D4ECB2", stats: { strength: 7, dexterity: 4, defense: 4, speed: 7 } },
  { name: "Gnash", weapon1: "Hammer", weapon2: "Spear", accentColor: "#F9B52B", stats: { strength: 7, dexterity: 3, defense: 5, speed: 7 } },
  { name: "Hattori", weapon1: "Sword", weapon2: "Spear", accentColor: "#CC0000", stats: { strength: 4, dexterity: 6, defense: 4, speed: 8 } },
  { name: "Imugi", weapon1: "Axe", weapon2: "Greatsword", accentColor: "#495551", stats: { strength: 8, dexterity: 3, defense: 8, speed: 3 } },
  { name: "Isaiah", weapon1: "Blasters", weapon2: "Cannon", accentColor: "#4C4040", stats: { strength: 5, dexterity: 6, defense: 7, speed: 4 } },
  { name: "Jaeyun", weapon1: "Sword", weapon2: "Greatsword", accentColor: "#F3D66A", stats: { strength: 6, dexterity: 5, defense: 5, speed: 6 } },
  { name: "Jhala", weapon1: "Sword", weapon2: "Axe", accentColor: "#431834", stats: { strength: 7, dexterity: 7, defense: 3, speed: 5 } },
  { name: "Jiro", weapon1: "Sword", weapon2: "Scythe", accentColor: "#690a64", stats: { strength: 5, dexterity: 7, defense: 3, speed: 7 } },
  { name: "Kaya", weapon1: "Spear", weapon2: "Bow", accentColor: "#c1fffe", stats: { strength: 4, dexterity: 4, defense: 7, speed: 7 } },
  { name: "Koji", weapon1: "Sword", weapon2: "Bow", accentColor: "#9ba1ff", stats: { strength: 5, dexterity: 8, defense: 4, speed: 5 } },
  { name: "Kor", weapon1: "Hammer", weapon2: "Gauntlets", accentColor: "#f4d956", stats: { strength: 6, dexterity: 5, defense: 7, speed: 4 } },
  { name: "Lin Fei", weapon1: "Katars", weapon2: "Cannon", accentColor: "#CA3C2C", stats: { strength: 3, dexterity: 8, defense: 4, speed: 7 } },
  { name: "Loki", weapon1: "Katars", weapon2: "Scythe", accentColor: "#47B3BD", stats: { strength: 4, dexterity: 8, defense: 5, speed: 5 } },
  { name: "Lucien", weapon1: "Blasters", weapon2: "Katars", accentColor: "#808851", stats: { strength: 3, dexterity: 5, defense: 6, speed: 8 } },
  { name: "Magyar", weapon1: "Hammer", weapon2: "Greatsword", accentColor: "#0D587E", stats: { strength: 5, dexterity: 4, defense: 9, speed: 4 } },
  { name: "Mako", weapon1: "Katars", weapon2: "Greatsword", accentColor: "#589FA1", stats: { strength: 6, dexterity: 4, defense: 4, speed: 8 } },
  { name: "Mirage", weapon1: "Spear", weapon2: "Scythe", accentColor: "#F2D273", stats: { strength: 7, dexterity: 6, defense: 4, speed: 5 } },
  { name: "Mordex", weapon1: "Gauntlets", weapon2: "Scythe", accentColor: "#B8B7AF", stats: { strength: 6, dexterity: 4, defense: 5, speed: 7 } },
  { name: "Munin", weapon1: "Bow", weapon2: "Scythe", accentColor: "#474E60", stats: { strength: 5, dexterity: 6, defense: 4, speed: 7 } },
  { name: "Qinghua & Baobao", weapon1: "Cannon", weapon2: "Orb", accentColor: "#FF7D7F", stats: { strength: 5, dexterity: 4, defense: 5, speed: 8 } },
  { name: "Queen Nai", weapon1: "Spear", weapon2: "Katars", accentColor: "#7e1e88", stats: { strength: 7, dexterity: 4, defense: 8, speed: 3 } },
  { name: "Nix", weapon1: "Blasters", weapon2: "Scythe", accentColor: "#221440", stats: { strength: 4, dexterity: 5, defense: 7, speed: 6 } },
  { name: "Onyx", weapon1: "Gauntlets", weapon2: "Cannon", accentColor: "#63F6FB", stats: { strength: 5, dexterity: 4, defense: 8, speed: 5 } },
  { name: "Orion", weapon1: "Rocket Lance", weapon2: "Spear", accentColor: "#FFA70B", stats: { strength: 4, dexterity: 6, defense: 6, speed: 6 } },
  { name: "Petra", weapon1: "Gauntlets", weapon2: "Orb", accentColor: "#80012A", stats: { strength: 8, dexterity: 4, defense: 4, speed: 6 } },
  { name: "Priya", weapon1: "Sword", weapon2: "Chakram", accentColor: "#ED3614", stats: { strength: 4, dexterity: 6, defense: 5, speed: 7 } },
  { name: "Ragnir", weapon1: "Katars", weapon2: "Axe", accentColor: "#F15850", stats: { strength: 5, dexterity: 6, defense: 6, speed: 5 } },
  { name: "Ransom", weapon1: "Bow", weapon2: "Chakram", accentColor: "#120276", stats: { strength: 7, dexterity: 4, defense: 3, speed: 8 } },
  { name: "Rayman", weapon1: "Axe", weapon2: "Gauntlets", accentColor: "#FFD589", stats: { strength: 5, dexterity: 5, defense: 6, speed: 6 } },
  { name: "Red Raptor", weapon1: "Battle Boots", weapon2: "Orb", accentColor: "#A71E2B", stats: { strength: 6, dexterity: 6, defense: 4, speed: 6 } },
  { name: "Reno", weapon1: "Blasters", weapon2: "Orb", accentColor: "#D6C68B", stats: { strength: 4, dexterity: 7, defense: 6, speed: 5 } },
  { name: "Sir Roland", weapon1: "Sword", weapon2: "Rocket Lance", accentColor: "#FAD76B", stats: { strength: 5, dexterity: 5, defense: 8, speed: 4 } },
  { name: "Rupture", weapon1: "Rocket Lance", weapon2: "Katars", accentColor: "#EC007D", stats: { strength: 9, dexterity: 3, defense: 5, speed: 5 } },
  { name: "Scarlet", weapon1: "Hammer", weapon2: "Rocket Lance", accentColor: "#FAE493", stats: { strength: 8, dexterity: 5, defense: 5, speed: 4 } },
  { name: "Sentinel", weapon1: "Hammer", weapon2: "Katars", accentColor: "#1F23CE", stats: { strength: 5, dexterity: 4, defense: 7, speed: 6 } },
  { name: "Seven", weapon1: "Spear", weapon2: "Cannon", accentColor: "#EBEAD5", stats: { strength: 7, dexterity: 3, defense: 8, speed: 4 } },
  { name: "Sidra", weapon1: "Sword", weapon2: "Cannon", accentColor: "#FDFCFF", stats: { strength: 6, dexterity: 4, defense: 6, speed: 6 } },
  { name: "Teros", weapon1: "Hammer", weapon2: "Axe", accentColor: "#fbb52a", stats: { strength: 8, dexterity: 3, defense: 6, speed: 5 } },
  { name: "Tezca", weapon1: "Gauntlets", weapon2: "Battle Boots", accentColor: "#ECE1E3", stats: { strength: 7, dexterity: 5, defense: 5, speed: 5 } },
  { name: "Thatch", weapon1: "Sword", weapon2: "Blasters", accentColor: "#A21125", stats: { strength: 7, dexterity: 5, defense: 3, speed: 7 } },
  { name: "Thea", weapon1: "Rocket Lance", weapon2: "Battle Boots", accentColor: "#FFFE9A", stats: { strength: 4, dexterity: 6, defense: 3, speed: 9 } },
  { name: "Thor", weapon1: "Hammer", weapon2: "Orb", accentColor: "#AF1003", stats: { strength: 6, dexterity: 4, defense: 7, speed: 5 } },
  { name: "Ulgrim", weapon1: "Rocket Lance", weapon2: "Axe", accentColor: "#536F6B", stats: { strength: 6, dexterity: 3, defense: 7, speed: 6 } },
  { name: "Val", weapon1: "Sword", weapon2: "Gauntlets", accentColor: "#1faed2", stats: { strength: 4, dexterity: 5, defense: 6, speed: 7 } },
  { name: "Vector", weapon1: "Rocket Lance", weapon2: "Bow", accentColor: "#FA777C", stats: { strength: 5, dexterity: 4, defense: 6, speed: 7 } },
  { name: "Lady Vera", weapon1: "Scythe", weapon2: "Chakram", accentColor: "#FA777C", stats: { strength: 3, dexterity: 7, defense: 8, speed: 4 } },
  { name: "Vivi", weapon1: "Blasters", weapon2: "Battle Boots", accentColor: "#600AFD", stats: { strength: 6, dexterity: 5, defense: 4, speed: 7 } },
  { name: "Volkov", weapon1: "Axe", weapon2: "Scythe", accentColor: "#A13A4C", stats: { strength: 4, dexterity: 8, defense: 6, speed: 4 } },
  { name: "Lord Vraxx", weapon1: "Blasters", weapon2: "Rocket Lance", accentColor: "#00FFCC", stats: { strength: 4, dexterity: 8, defense: 4, speed: 6 } },
  { name: "Wu Shang", weapon1: "Spear", weapon2: "Gauntlets", accentColor: "#FFDD66", stats: { strength: 5, dexterity: 7, defense: 5, speed: 5 } },
  { name: "Xull", weapon1: "Axe", weapon2: "Cannon", accentColor: "#6E7E47", stats: { strength: 9, dexterity: 4, defense: 5, speed: 4 } },
  { name: "Yumiko", weapon1: "Hammer", weapon2: "Bow", accentColor: "#00e5ff", stats: { strength: 4, dexterity: 7, defense: 4, speed: 7 } },
  { name: "Zariel", weapon1: "Bow", weapon2: "Gauntlets", accentColor: "#fdf8a2", stats: { strength: 7, dexterity: 4, defense: 7, speed: 4 } },
  { name: "King Zuva", weapon1: "Hammer", weapon2: "Battle Boots", accentColor: "#3F251C", stats: { strength: 8, dexterity: 4, defense: 6, speed: 4 } }
];